(async()=>{
  const root=QD.q('#paperRoot'), error=QD.q('#errorBox'), file=QD.getParam('file');
  QD.q('#backBtn').onclick=()=>history.length>1?history.back():QD.go('index.html');
  QD.q('#homeBtn').onclick=()=>QD.go('index.html');
  QD.q('#printBtn').onclick=()=>window.print();
  if(!file){error.textContent='No study file selected. Go back to the library.';error.classList.remove('hidden');return}
  try{const s=await QD.loadJSON(file+'.json');render(s)}catch(e){error.textContent=e.message;error.classList.remove('hidden')}

  function render(s){
    document.title=`${s.project.pdf_id} · ${s.study_range.surah_name} ${s.study_range.range}`;
    QD.q('#toolbarTitle').textContent=`${s.project.pdf_id} · ${s.study_range.surah_name} · ${s.study_range.range}`;
    const m={pdf_id:s.project.pdf_id,surah_name:s.study_range.surah_name,range:s.study_range.range};
    let pages=[];
    pages.push(QD.page(`<div class="cover"><div class="page-content"><div class="page-kicker">${QD.escape(s.project.name)}</div><h1 class="page-title">${QD.escape(s.study_range.surah_name)}</h1><div class="range">Ayat ${QD.escape(s.study_range.ayah_start)}–${QD.escape(s.study_range.ayah_end)}</div><div class="cover-rule"></div><p class="lead">${QD.escape(s.surah_info.name_meaning||'Deep Quran study')}</p><div class="meta-grid"><div class="meta-item"><b>PDF ID</b><span>${QD.escape(s.project.pdf_id)}</span></div><div class="meta-item"><b>Revelation</b><span>${QD.escape(s.surah_info.classification?.makki_or_madani||'')}</span></div><div class="meta-item"><b>Ayat</b><span>${QD.escape(s.study_range.range)}</span></div><div class="meta-item"><b>Language</b><span>Natural Hinglish</span></div></div></div></div>`,m,'cover'));
    pages.push(QD.page(`<div class="section-label">📚 Study Library</div><h1 class="page-title">Contents</h1><p class="lead">Is PDF mein pehle poora passage, phir section-wise flow aur ayat-by-ayat deep study hai.</p><ul class="toc-list"><li><span>Surah Introduction</span><b>01</b></li><li><span>Complete Passage</span><b>02</b></li>${s.sections.map((x,i)=>`<li><span>${QD.escape(x.title)} · ${QD.escape(x.ayah_range)}</span><b>${String(i+3).padStart(2,'0')}</b></li>`).join('')}<li><span>PDF Range Conclusion</span><b>End</b></li><li><span>Surah Conclusion</span><b>End</b></li><li><span>Sources & Quality Control</span><b>End</b></li></ul><div class="callout">💡 <b>Reading rule:</b> Arabic → transliteration → Roman Urdu → English meaning → Simple → Deep. Modern application ko tafsir ka substitute nahi samjho.</div>`,m));
    pages.push(QD.page(`<div class="section-label">🧭 Surah Introduction</div><h1 class="page-title">${QD.escape(s.study_range.surah_name)} · Background</h1><p class="lead">${QD.escape(s.surah_info.introduction)}</p><div class="two-col"><div class="depth-box"><h3>Kya?</h3><p>${QD.escape(s.surah_info.what)}</p></div><div class="depth-box"><h3>Kyun?</h3><p>${QD.escape(s.surah_info.why)}</p></div><div class="depth-box"><h3>Kab / Kahan?</h3><p>${QD.escape(s.surah_info.when_where)}</p></div><div class="depth-box"><h3>Kaise padhna?</h3><p>${QD.escape(s.surah_info.how_to_study)}</p></div></div><div class="callout gold"><b>Known vs debated:</b> ${QD.escape(s.surah_info.known_vs_debated)}</div><h3>Main themes</h3><p>${s.surah_info.themes.map(x=>`<span class="badge">${QD.escape(x)}</span>`).join(' ')}</p>`,m));
    pages.push(QD.page(`<div class="section-label">📖 Complete Passage</div><h1 class="page-title">Pehle poora passage ek saath padho</h1>${s.complete_passage.ayahs.map(a=>`<div class="depth-box"><div class="ayah-header"><h3>Ayat ${a.ayah}</h3><span class="ayah-number">${QD.escape(a.reference)}</span></div><div class="arabic">${a.arabic}</div><p class="translit">${QD.escape(a.transliteration)}</p><p class="meaning"><strong>Roman Urdu:</strong> ${QD.escape(a.roman_urdu)}</p><p class="meaning"><strong>English:</strong> ${QD.escape(a.english_meaning)}</p></div>`).join('')}`,m));
    s.sections.forEach(sec=>pages.push(QD.page(`<div class="section-label">🧩 Section</div><h1 class="page-title">${QD.escape(sec.title)}</h1><div class="pill">Ayat ${QD.escape(sec.ayah_range)}</div><p class="lead">${QD.escape(sec.theme)}</p><div class="depth-box"><h3>Flow</h3><p>${QD.escape(sec.flow)}</p></div><div class="depth-box"><h3>Section summary</h3><p>${QD.escape(sec.summary)}</p></div><div class="callout">${QD.escape(sec.study_note)}</div>`,m)));
    s.ayahs.forEach(a=>{
      const words=(a.important_arabic_words||[]).map(w=>`<tr><td dir="rtl" lang="ar">${w.arabic}</td><td>${QD.escape(w.transliteration)}</td><td>${QD.escape(w.meaning)}</td><td>${QD.escape(w.root)}</td><td>${QD.escape(w.word_form)}</td><td>${QD.escape(w.literal_meaning)}</td><td>${QD.escape(w.contextual_meaning)}</td></tr>`).join('');
      pages.push(QD.page(`<div class="section-label">📝 Ayat-by-ayat Study</div><div class="ayah-header"><h1 class="page-title">Ayat ${a.ayah}</h1><span class="ayah-number">${QD.escape(a.reference)}</span></div><div class="arabic">${a.arabic}</div><p class="translit"><b>Transliteration:</b> ${QD.escape(a.transliteration)}</p><p class="meaning"><strong>Roman Urdu:</strong> ${QD.escape(a.roman_urdu)}</p><p class="meaning"><strong>English:</strong> ${QD.escape(a.english_meaning)}</p><div class="depth-box"><h3>🟢 Simple</h3><p>${QD.escape(a.simple)}</p></div><div class="depth-box"><h3>🔎 Deep</h3><p>${QD.escape(a.deep)}</p></div><div class="two-col"><div class="depth-box"><h3>Main message</h3><p>${QD.escape(a.main_message)}</p></div><div class="depth-box"><h3>Why it matters</h3><p>${QD.escape(a.why_it_matters)}</p></div></div>`,m));
      pages.push(QD.page(`<div class="section-label">🔬 Ayat ${a.ayah} · Detail</div><h1 class="page-title">Arabic words & language</h1><table class="word-table"><thead><tr><th>Arabic</th><th>Transliteration</th><th>Meaning</th><th>Root</th><th>Form</th><th>Literal</th><th>Context</th></tr></thead><tbody>${words}</tbody></table><div class="two-col"><div class="depth-box"><h3>Grammar / rhetoric</h3><p>${QD.escape(a.grammar_rhetoric)}</p></div><div class="depth-box"><h3>Context</h3><p>${QD.escape(a.historical_context)}</p></div></div><div class="callout"><b>Common misunderstanding:</b> ${QD.escape(a.common_misunderstandings)}</div><div class="callout gold"><b>What it does not mean:</b> ${QD.escape(a.what_it_does_not_mean)}</div>`,m));
      pages.push(QD.page(`<div class="section-label">🌍 Connections</div><h1 class="page-title">Ayat ${a.ayah} · Connections & application</h1><div class="two-col"><div class="depth-box"><h3>Quran connections</h3><p>${QD.escape(a.connected_ayat)}</p></div><div class="depth-box"><h3>Hadith</h3><p>${QD.escape(a.hadith?.summary||'No specific Hadith added.')}</p>${a.hadith?.reference?`<small>${QD.escape(a.hadith.reference)} · ${QD.escape(a.hadith.status||'')}</small>`:''}</div><div class="depth-box"><h3>History / archaeology</h3><p>${QD.escape(a.history_evidence||'Not central to this ayah; no forced historical claim.')}</p></div><div class="depth-box"><h3>Science</h3><p>${QD.escape(a.science?.summary||'No scientific claim needed for this ayah.')}</p>${a.science?.status?`<span class="badge ${a.science.status_class}">${QD.escape(a.science.status)}</span>`:''}</div></div><div class="depth-box"><h3>Real-life example</h3><p>${QD.escape(a.real_life_example)}</p></div><div class="depth-box"><h3>Modern Life Connection <small>(application, tafsir nahi)</small></h3><p>${QD.escape(a.modern_world_connection)}</p></div>`,m));
      pages.push(QD.page(`<div class="section-label">🧠 Reflection</div><h1 class="page-title">Ayat ${a.ayah} · Think → Act</h1><div class="two-col"><div class="depth-box"><h3>Known / debated / unknown</h3><p>${QD.escape(a.knowledge_status)}</p></div><div class="depth-box"><h3>Future / forward-looking context</h3><p>${QD.escape(a.future_or_forward_looking_context)}</p></div></div><div class="depth-box"><h3>Q&A</h3><p>${a.qa.map(q=>`<b>Q:</b> ${QD.escape(q.q)}<br><b>A:</b> ${QD.escape(q.a)}<br><br>`).join('')}</p></div><div class="two-col"><div class="depth-box"><h3>Night reflection</h3><p>${QD.escape(a.night_reflection)}</p></div><div class="depth-box"><h3>Personal action</h3><p>${QD.escape(a.personal_action)}</p></div></div><div class="notes-box"></div><small>Personal notes</small>`,m));
    });
    pages.push(QD.page(`<div class="section-label">🎯 PDF-range Conclusion</div><h1 class="page-title">${QD.escape(s.study_range.range)} · What should stay with me?</h1><div class="conclusion-card"><p>${QD.escape(s.pdf_range_conclusion.complete_summary)}</p></div><div class="action-grid" style="margin-top:14px">${[['What',s.pdf_range_conclusion.what_it_teaches],['Why',s.pdf_range_conclusion.why_it_matters],['What to do',s.pdf_range_conclusion.what_i_should_do],['How',s.pdf_range_conclusion.how_to_apply],['What to avoid',s.pdf_range_conclusion.what_to_avoid],['One-line reminder',s.pdf_range_conclusion.one_sentence_reminder]].map(x=>`<div class="depth-box"><h3>${x[0]}</h3><p>${QD.escape(x[1])}</p></div>`).join('')}</div>`,m));
    pages.push(QD.page(`<div class="section-label">🌙 Surah Conclusion</div><h1 class="page-title">${QD.escape(s.study_range.surah_name)} · Full Surah Synthesis</h1><div class="conclusion-card"><p>${QD.escape(s.surah_conclusion.complete_summary)}</p></div><div class="two-col" style="margin-top:12px">${[['What it teaches',s.surah_conclusion.what_it_teaches],['Why it matters',s.surah_conclusion.why_it_matters],['What I should understand',s.surah_conclusion.what_i_should_understand],['What I should do',s.surah_conclusion.what_i_should_do],['How to apply',s.surah_conclusion.how_to_apply],['What to avoid',s.surah_conclusion.what_to_avoid]].map(x=>`<div class="depth-box"><h3>${x[0]}</h3><p>${QD.escape(x[1])}</p></div>`).join('')}</div><div class="callout"><b>One-sentence lesson:</b> ${QD.escape(s.surah_conclusion.one_sentence_lesson)}<br><b>One-sentence action:</b> ${QD.escape(s.surah_conclusion.one_sentence_action)}</div>`,m));
    pages.push(QD.page(`<div class="section-label">🔍 Sources & QA</div><h1 class="page-title">Research Notes</h1><div class="qa-grid">${Object.entries(s.quality_control).filter(([k])=>k!=='notes').map(([k,v])=>`<div class="qa"><b>${QD.escape(k)}</b><span>${QD.escape(typeof v==='object'?JSON.stringify(v):v)}</span></div>`).join('')}</div><h3>Sources</h3><ul class="source-list">${s.sources.map(x=>`<li><b>${QD.escape(x.type)}:</b> ${QD.escape(x.title)} · ${QD.escape(x.reference)} ${x.url?`· <a href="${QD.escape(x.url)}" target="_blank" rel="noopener">source</a>`:''}</li>`).join('')}</ul><div class="callout">${QD.escape(s.project.human_review_note||'AI-generated study content; human scholarly review has not been performed.')}</div>`,m));
    root.innerHTML=pages.join('');QD.numberPages(root);
  }
})();
